version: "3"
services:
  sharecraft:
    depends_on:
      - sharecraft-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: sharecraft
    container_name: "sharecraft"
    ports:
      - "8080:8080"
    env_file:
      - .env
