version: "3"
services:
  sharecraft:
    build:
      context: .
      dockerfile: Dockerfile
    image: sharecraft
    container_name: "sharecraft"
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - sharecraft_net
networks:
  sharecraft_net:
