version: "3"
services:
  sharecraft:
    image: registry.cn-hangzhou.aliyuncs.com/supercll/craft-fe:{{tag}}
    container_name: "sharecraft"
    volumes:
      - /home/lc/nginx/:/etc/nginx/cert/
    ports:
      # - "8080:8080"
      - "4433:443"
    env_file:
      - .env